version: "3"
services:
  api:
    build: ../../.
    restart: always
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - ./.env
    volumes:
      - ../../src:/var/www/html/src
      - ../../test:/var/www/html/test
      - ../../views:/var/www/html/views
      - ../../public:/var/www/html/public
    depends_on:
      - mongo
  swagger:
    build: ../../_doc
    ports:
      - 3030:80
    environment:
      - API_VERSION=0.0.1
      - API_HOST=localhost:3000
    depends_on:
      - api
  mongo:
    image: mongo
    ports:
      - 27018:27017
    restart: always
    volumes:
      - ./datadb:/data/db
