version: "3"
services:
  api:
    build: ../../.
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - mongo
      - amqp
  swagger:
    build: ../../_doc
    ports:
      - 3030:80
    environment:
      - API_VERSION=0.0.1
      - API_HOST=localhost:3000
    depends_on:
      - api
  mongo:
    image: mongo
    ports:
      - 27018:27017
    restart: always
    volumes:
      - ./datadb:/data/db
